# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otherwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Otherwindow(object):
    def setupUi(self, Otherwindow):
        Otherwindow.setObjectName("Otherwindow")
        Otherwindow.resize(240, 320)
        self.centralwidget = QtWidgets.QWidget(Otherwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 100, 241, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 220, 93, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 101, 41))
        self.label.setObjectName("label")
        Otherwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Otherwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 26))
        self.menubar.setObjectName("menubar")
        Otherwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Otherwindow)
        self.statusbar.setObjectName("statusbar")
        Otherwindow.setStatusBar(self.statusbar)

        self.retranslateUi(Otherwindow)
        QtCore.QMetaObject.connectSlotsByName(Otherwindow)

    def retranslateUi(self, Otherwindow):
        _translate = QtCore.QCoreApplication.translate
        Otherwindow.setWindowTitle(_translate("Otherwindow", "MainWindow"))
        self.pushButton.setText(_translate("Otherwindow", "DATA OF PLAYERS"))
        self.checkBox.setText(_translate("Otherwindow", "CheckBox"))
        self.pushButton_2.setText(_translate("Otherwindow", "KNOCKOUT"))
        self.pushButton_3.setText(_translate("Otherwindow", "LEAGUE"))
        self.pushButton_4.setText(_translate("Otherwindow", "GENERATE"))
        self.label.setText(_translate("Otherwindow", "      ATHLOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Otherwindow = QtWidgets.QMainWindow()
    ui = Ui_Otherwindow()
    ui.setupUi(Otherwindow)
    Otherwindow.show()
    sys.exit(app.exec_())
